### ISSUE TITLE
Low quality of the bear scene

### ISSUE THREAD

**Issue by liru0126** [ayaanzhaque/instruct-nerf2nerf#60] opened 2023-09-06 10:16 UTC
I use the following command to edit the bear scene:
`ns-train in2n --data ../dataset/bear/ --load-dir ./outputs/bear/nerfacto/2023-09-05_083218/nerfstudio_models/ --pipeline.prompt "Turn the bear into a grizzly bear" --pipeline.guidance-scale 6.5 --pipeline.image-guidance-scale 1.5  nerfstudio-data --downscale-factor 2`
However, the results are unsatisfactory. I searched the issues of the git and found that the selection of guidance-scale and image-guidance scale is important. Could you please provide some advice about the training commands of the scenes in your paper?
The following is the result when editing the bear scene.
![截屏2023-09-06 18 06 20](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/37427071/4f668d99-924f-4075-8f3b-4a2b3d606359)

**Comment by liru0126** [comment] 2023-09-07 10:03
Thanks for your reply. I re-trained the original NeRF using:
`ns-train nerfacto --data ../dataset/bear/ nerfstudio-data --downscale-factor 2`
and the editing NeRF using the aforementioned command. The results are still unsatisfactory. 
Looking forward to your results.

**Comment by liru0126** [comment] 2023-09-07 10:05
> Thanks for your reply. I re-trained the original NeRF using: `ns-train nerfacto --data ../dataset/bear/ nerfstudio-data --downscale-factor 2` and the editing NeRF using the aforementioned command. The results are still unsatisfactory. Looking forward to your results.

 Original NeRF converges quickly and can generate high-quality videos.

**Comment by CaffeyChen** [comment] 2023-09-13 10:12
I got the same low quality of the bear scene as yours. I think it might be a problem with iterating images.

**Comment by Friedrich-M** [comment] 2023-09-15 05:16
I've also met the same problem of face scene. When I visualized the rendered and edited images every iteration, I found the editing results showed much worse quality. Maybe it occurs due to some modification of the new NeRFStudio version 0.3.3.

**Comment by ayaanzhaque** [comment] 2023-09-17 04:10
I did some digging today, the main issue is that the edited images look a lot worse currently than they did before. At first I thought it was a diffusers issue, so I reverted diffusers, accelerate, and transformers back to a version I know worked well. However, it still seems to produce pretty bad images. This means it is likely something that happened with a newer Nerfstudio version. I will try out some older versions and see if that makes any difference.

**Comment by ayaanzhaque** [comment] 2023-09-17 04:12
It seems that it might be an issue with a newer version of diffusers. Let me confirm

**Comment by zhao-yiqun** [comment] 2023-09-27 15:41
@ayaanzhaque , Hi~ Does it mean that  it is beacause the high version of diffusers ?  I wonder what is the diffusers version you used in you implementation. Also, I use the new version of diffusers on huggingface, the image version are already wrong.

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/91787021/575cb922-4791-408f-8411-3746c5a739ba)

**Comment by zhao-yiqun** [comment] 2023-10-01 07:38
> It seems that it might be an issue with a newer version of diffusers. Let me confirm

 @ayaanzhaque Hi, I tried all six scenes in your paper, and found that only the bear scene lead to such low quality.  Have you ever found the reason about that? Thanks in advance for your reply.

**Comment by BPAWD** [comment] 2023-10-19 07:53
Hi, I try the campsite scene and the result is also different from the paper. With the following training script:
```
ns-train in2n \
  --data ./data/campsite-small/ \
  --load-dir ./outputs/campsite-small/nerfacto/original_scene/nerfstudio_models/ \
  --pipeline.prompt {"Make it look like it just snowed"} \
  --pipeline.image-guidance-scale 1.5 \
  --pipeline.guidance-scale 7.5 \
```
I got some result like:
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/140590484/625968a8-8c4c-44f9-889d-2f5711b71a81)
All the people disapear.

**Comment by BPAWD** [comment] 2023-10-23 02:27
> > It seems that it might be an issue with a newer version of diffusers. Let me confirm
> 
> @ayaanzhaque Hi, I tried all six scenes in your paper, and found that only the bear scene lead to such low quality. Have you ever found the reason about that? Thanks in advance for your reply.

Hi, did you get good result on other scene like campsite and farm-small, my results on these two scenes are not as good as the paper.

**Comment by ttaa9** [comment] 2023-10-29 02:00
> It seems that it might be an issue with a newer version of diffusers. Let me confirm

Did you confirm that it is the diffusers version vs nerfstudio version vs something else?

**Comment by hrz2000** [comment] 2023-10-29 13:49
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/272692f0-fb50-4b67-8eef-49c8f20124e9)
I find it very easy to edit poor quality images as  in the above picture  for p2p for nerfstudio rendered images, which is very common(but not very common for non-rendered images), and I wonder why this is because

**Comment by ayaanzhaque** [comment] 2023-11-01 22:29
@lsongx can u share what diffusers version you have?

**Comment by lsongx** [comment] 2023-11-01 22:41
diffusers version  0.21.4

here is an example of the output from `edit_image` in `ip2p.py`

cond_im

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/176f72cd-1df1-45b5-9632-3b00f195d5df)

output
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/849988dd-5abc-4aa7-91b9-de3b491cd595)

command used:
```
ns-train in2n --data bear --load-dir bear/nerfacto/default/nerfstudio_models --pipeline.prompt "Turn the bear into a grizzly bear" --pipeline.guidance-scale 6.5 --pipeline.image-guidance-scale 1.5  nerfstudio-data --downscale-factor 2
```

**Comment by ayaanzhaque** [comment] 2023-11-01 23:11
What is your nerfstudio version?

**Comment by ayaanzhaque** [comment] 2023-11-01 23:12
And is this the trained NeRF or just an edited render?

**Comment by ayaanzhaque** [comment] 2023-11-01 23:14
And can you share your versions for transformers and accelerate?

**Comment by lsongx** [comment] 2023-11-01 23:44
nerfstudio 0.3.4 with `e8cee3fd`
transformers 4.34.1
accelerate.__version__ '0.23.0'

**Comment by ayaanzhaque** [comment] 2023-11-01 23:50
Can you share your results after training the entire thing?

**Comment by lsongx** [comment] 2023-11-02 02:14
I see the issue now... After 3500iters

https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/86e194c9-93ba-4f7c-a01a-8179153e432c

**Comment by ayaanzhaque** [comment] 2023-11-02 02:22
Ya this seems like an issue with the images being edited weirdly, can you try printing some of the images around this many iterations

**Comment by lsongx** [comment] 2023-11-03 01:50
Hi @ayaanzhaque , I saved the images out: some are good, some are bad. 

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/4d14471a-c125-4ee4-b304-c2ba44df870a)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/f9594fd7-1558-4b33-bb73-b1ff58b082bf)

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/a4befd08-52a8-41d5-b050-4b24b869523e)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/275b75f6-3117-4bb6-81fe-678b59b16871)

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/ed8178ed-7db1-4983-a271-097c759a56b0)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/a4546700-75f9-477c-972e-b3a4fbc612f1)

I tried the original version of ip2p (not updated since Jan, https://github.com/timothybrooks/instruct-pix2pix) 
<img width="1536" alt="Screenshot 2023-11-02 at 6 46 57 PM" src="https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/b4eb2fdf-eda7-4f69-8e02-aa687ca58218">

My understanding is that it is fine if the instructp2p doesn't get good results on some views, as long as it works on some views. Do you think this is really due to instructp2p diffuser pipeline? I tend to assume that something in nerfstudio has changed.

**Comment by lsongx** [comment] 2023-11-03 17:41
@ayaanzhaque I think I found out the reason. It is due to camera optimizer. Now after 3500 iters.

https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/12553253/84cbc8ce-03fe-4687-975a-176d0fc3e6ea

**Comment by ayaanzhaque** [comment] 2023-11-03 17:55
Ah, thank you!! So turning off the camera optimizer seems to fix the issue?

**Comment by lsongx** [comment] 2023-11-03 18:16
I submitted a PR, but not sure if this can solve other guys' problem. Maybe merge after get confirmed by them.

@ttaa9 @liru0126 @CaffeyChen @BPAWD @zhao-yiqun Do you mind giving this a try: https://github.com/ayaanzhaque/instruct-nerf2nerf/pull/74

**Comment by hrz2000** [comment] 2023-11-04 02:22
I just used the strategy you proposed, and I still have the problems you encountered before (but it is better than my previous results) I wonder if anyone else has the same problem as me
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/ddb82603-c480-46bb-bbd6-c7f1f2a50f27)

**Comment by lsongx** [comment] 2023-11-04 03:43
@hrz2000 Thanks for testing! Could you pull that PR with `git clone git@github.com:lsongx/instruct-nerf2nerf.git` and then do `pip install -e .` again?

**Comment by hrz2000** [comment] 2023-11-04 06:28
@lsongx , I did as you said, but the result is still not good
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/95303e27-83e0-49b1-a022-c675e20bf9fa)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/cd09e3c6-4075-4e31-8b3b-588f73bae4b5)
<img width="1306" alt="image" src="https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/d6e53f24-76fb-4407-9084-041fb028170d">
My instructions are：
```
ns-train in2n --data '/root/picasso/hrz2000/workplace/DreamEditor/data/bear' \
--load-dir ../instruct-nerf2nerf/outputs/bear/nerfacto/2023-10-24_120015/nerfstudio_models \
--pipeline.prompt "Turn the bear into a grizzly bear" \
--pipeline.guidance-scale 6.5 \
--pipeline.image-guidance-scale 1.5  \
nerfstudio-data --downscale-factor 4
```
If the down-sampling factor is 1, this result will be produced
<img width="1210" alt="image" src="https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/63ffad4c-802f-484d-aee9-1c4b513e1712">

**Comment by hrz2000** [comment] 2023-11-04 07:25
When I retrained the nerf model 2.2 w step and edited it 2k steps, the result seemed much better (this time I didn't load the optimizer's error)

https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/79900945/3fc86dd4-e686-41d5-9bfa-9458506c00c3

**Comment by ayaanzhaque** [comment] 2023-11-04 07:26
Ok cool, looks like the camera optimizer is the issue. I'll go ahead and merge the PR!

**Comment by Iliceth** [comment] 2023-11-09 01:42
I have done several attempts with:

`ns-train in2n-small --data data/nerfstudio/bear --load-dir outputs/bear/nerfacto/2023-11-08_215410/nerfstudio_models --pipeline.prompt "make it a grizzly bear" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5 nerfstudio-data --downscale-factor 2`

But the results always turn to something similar as below:

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/68381834/400dd3db-0534-4307-9292-4e120fcb4aa6)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/68381834/7fcf7eeb-ec75-447d-ab14-033619f8404e)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/68381834/25f08797-e6b0-48f6-a12d-f19c6b6bbae3)
![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/68381834/75286cae-9cb3-4708-9ba0-e8f7fe576dd0)

The code used it the one after the update from a few days ago.

**Comment by lsongx** [comment] 2023-11-09 23:05
@Iliceth Could you try completely removing existing in2n and nerfstudio, and reinstalling them again? You can use
```
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```
for nerfstudio. Also, did you try `in2n`? I didn't test `in2n-small`.

**Comment by Iliceth** [comment] 2023-11-10 02:56
> @Iliceth Could you try completely removing existing in2n and nerfstudio, and reinstalling them again? You can use
> 
> ```
> git clone https://github.com/nerfstudio-project/nerfstudio.git
> cd nerfstudio
> pip install --upgrade pip setuptools
> pip install -e .
> ```
> 
> for nerfstudio. Also, did you try `in2n`? I didn't test `in2n-small`.

@lsongx I was under the impression I had the latest version, as I had done my re-install just after the camera optimizer update was done. But created a new env, installed the dependencies, `nerfstudio` and `in2n` anyhow, as you requested. Ran `in2n-small` (as I only have 12 GB) again first and success, got the output I expected. :-) Have extra changes been implemented in the last days?

![image](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/68381834/4fbc5ba6-4d06-4687-b923-4a03819dfe64)

**Comment by lsongx** [comment] 2023-11-10 16:47
Yeah there is a PR merged last week

**Comment by ayaanzhaque** [comment] 2023-11-13 05:40
So is this issue resolved @lsongx?

**Comment by lsongx** [comment] 2023-11-15 19:37
@ayaanzhaque Yeah, I'd say so. It's working great for me now. Not sure about everyone else on this thread, though.

**Closed** 2023-12-21 02:42 UTC
